package com.pumpkin.intellij.workflow.processed;

import com.intellij.codeInsight.completion.CompletionContributor;
import com.intellij.codeInsight.completion.CompletionParameters;
import com.intellij.codeInsight.completion.CompletionProvider;
import com.intellij.codeInsight.completion.CompletionResultSet;
import com.intellij.codeInsight.completion.CompletionType;
import com.intellij.codeInsight.completion.CompletionUtilCore;
import com.intellij.codeInsight.completion.InsertionContext;
import com.intellij.codeInsight.completion.PlainPrefixMatcher;
import com.intellij.codeInsight.lookup.LookupElementBuilder;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.module.Module;
import com.intellij.openapi.module.ModuleUtilCore;
import com.intellij.openapi.vfs.VfsUtilCore;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.patterns.PlatformPatterns;
import com.intellij.psi.PsiElement;
import com.intellij.psi.PsiFile;
import com.intellij.psi.util.PsiTreeUtil;
import com.intellij.util.ProcessingContext;
import com.pumpkin.intellij.endpoint.SwitchMethodEditor;
import com.pumpkin.intellij.util.FeatureFilePaths;
import com.pumpkin.intellij.util.GherkinPsiUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.plugins.cucumber.psi.GherkinStep;
import org.jetbrains.plugins.cucumber.psi.GherkinTableCell;

import java.util.List;

/**
 * Schema-driven autocomplete for {@code outgoing payload is compliant with template &lt;path&gt;}
 * steps (see {@link GherkinPsiUtil#isOutgoingPayloadStep}, generated by the {@code dwf:} shortcut
 * - {@link ProcessedWorkflowAssertionGenerator}). Offers every existing template file under the
 * current feature file's own {@code XX} folder's {@code templates} directory - the {@code XX}
 * *name* comes from {@link FeatureFilePaths#resolveDirTwoLevelsBelowFeatures} (the feature file's
 * own {@code features/.../XX/...} ancestry), but the actual {@code templates} directory is then
 * looked up across every module source root via {@link OutgoingPayloadTemplates#findTemplatesDir}
 * - the same search {@code OutgoingPayloadTemplateResolver} uses to create these files in the
 * first place, since a template can live under a completely different source root than the
 * feature files themselves (e.g. {@code src/main/resources/XX/templates/...} while features live
 * under {@code src/test/resources/features/.../XX/...}) - a template from a *different* {@code XX}
 * would never be a valid path from this file anyway, per that same resolver's own convention.
 *
 * <p>Selecting one inserts its full {@code /XX/templates/.../....json} path and - if the step has
 * no table yet - a 2-row table right below it, both built by {@link OutgoingPayloadTemplates}
 * (shared with the {@code op:} shortcut - {@link OutgoingPayloadTriggerHandler}): header row =
 * every required field (a bare {@code %name%} placeholder with no {@code :default} suffix), one
 * blank data row, caret in the blank row's first cell.
 */
public class OutgoingPayloadTemplateCompletionContributor extends CompletionContributor {

    public OutgoingPayloadTemplateCompletionContributor() {
        extend(CompletionType.BASIC,
               PlatformPatterns.psiElement().inside(GherkinStep.class),
               new Provider());
    }

    private static final class Provider extends CompletionProvider<CompletionParameters> {

        @Override
        protected void addCompletions(@NotNull CompletionParameters parameters,
                                      @NotNull ProcessingContext context,
                                      @NotNull CompletionResultSet result) {

            PsiElement position = parameters.getPosition();
            if (PsiTreeUtil.getParentOfType(position, GherkinTableCell.class) != null) return; // step's own text only

            GherkinStep step = PsiTreeUtil.getParentOfType(position, GherkinStep.class);
            if (step == null || !GherkinPsiUtil.isOutgoingPayloadStep(step)) return;

            String stepName = step.getName();
            if (stepName == null) return;
            String typedPath = GherkinPsiUtil.getOutgoingPayloadPath(step);
            if (typedPath == null) return;
            // getOutgoingPayloadPath returns the FULL (possibly dummy-identifier-suffixed) text -
            // truncate at the caret the same way DbStepCompletionContributor does.
            typedPath = truncateAtCaret(typedPath).trim();

            PsiFile psiFile = step.getContainingFile();
            VirtualFile featureFile = psiFile == null ? null : psiFile.getVirtualFile();
            if (featureFile == null) return;
            VirtualFile xxDir = FeatureFilePaths.resolveDirTwoLevelsBelowFeatures(featureFile);
            if (xxDir == null) return;
            Module module = ModuleUtilCore.findModuleForFile(featureFile, psiFile.getProject());
            if (module == null) return;
            String xxName = xxDir.getName();
            VirtualFile templatesDir = OutgoingPayloadTemplates.findTemplatesDir(module, xxName);
            if (templatesDir == null) return;

            List<VirtualFile> candidates = OutgoingPayloadTemplates.findTemplateFiles(templatesDir);
            if (candidates.isEmpty()) return;

            CompletionResultSet prefixed = result.withPrefixMatcher(new PlainPrefixMatcher(typedPath));
            for (VirtualFile candidate : candidates) {
                String relative = VfsUtilCore.getRelativePath(candidate, templatesDir);
                if (relative == null) continue;
                String path = "/" + xxName + "/templates/" + relative;
                prefixed.addElement(LookupElementBuilder.create(path)
                        .withInsertHandler((ctx, item) -> onTemplateSelected(ctx, candidate)));
            }
        }

        /**
         * Inserts a header(required fields)+blank-row table right below the step, unless it
         * already has one (an existing table is left untouched, same "don't clobber existing
         * content" rule {@code DbStepCompletionContributor.onTableNameInserted} follows).
         */
        private static void onTemplateSelected(@NotNull InsertionContext context, @NotNull VirtualFile templateFile) {
            context.commitDocument();
            PsiElement pos = context.getFile().findElementAt(context.getStartOffset());
            GherkinStep step = PsiTreeUtil.getParentOfType(pos, GherkinStep.class, false);
            if (step == null || step.getTable() != null) return;

            List<String> fields = OutgoingPayloadTemplates.readRequiredFields(templateFile);
            if (fields.isEmpty()) return;

            Document document = context.getDocument();
            Editor editor = context.getEditor();
            String indent = SwitchMethodEditor.indentOf(document.getText(), step.getTextOffset());
            OutgoingPayloadTemplates.insertFieldsTable(document, editor, context.getTailOffset(), indent, fields);
        }

        /** Text up to the dummy identifier IntelliJ injects at the caret during completion. */
        private static @NotNull String truncateAtCaret(@NotNull String text) {
            int idx = text.indexOf(CompletionUtilCore.DUMMY_IDENTIFIER_TRIMMED);
            return idx >= 0 ? text.substring(0, idx) : text;
        }
    }
}
